title: STORMing Cancer
description: Projects and Data from the STORMing cancer CRUK grand-challenge
theme: just-the-docs

url: https://just-the-docs.github.io

# deactivate search for now
search_enabled: false


# aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Color scheme supports "light" (default) and "dark"
color_scheme: dark
